name: E2E test
on:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches:
    - 'main'
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  publish:
    if: github.repository_owner == vars.REPO_OWNER
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.IAM_ROLE_ARN}}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
          check-latest: true
      - name: Run E2E tests
        run: make e2e
